# CLasses in Python

In [33]:
class Item:

    # Clas variables
    pay_rate = 0.8 # Pay after 20 % discount
    all = []

    def __init__(self, name: str, price: float, quantity = 0):
        
        # Validations on received arguments
        assert price>=0, f"Price {price} must be greater than or equal to zero"
        assert quantity>=0, f"Price {quantity} must be greater than or equal to zero"

        
        # Initiaizing Instance variables
        self.name = name
        self.price = price
        self.quantity = quantity

        self.all.append(self)

    def total_amount(self):
        return self.price * self.quantity
    

    def apply_discount(self):
        self.price = self.price * self.pay_rate   # Item.pay_rate can also be written   


    # for better representation of all the instance attributes we use __repr__  magic method inside class
    def __repr__(self) -> str:
        return f"Item({self.name}, {self.price}, {self.quantity})"
    

    




In [2]:
# Creating Class Instances
item1 = Item("Mobile", 400, 3)
print(f"Total amount for {item1.name} is {item1.total_amount()}")



Total amount for Mobile is 1200


In [4]:
# Accessing class variable
print(Item.pay_rate)  # Through class nanme
print(item1.pay_rate)     # Through instance 

0.8
0.8


In [6]:
# Built in magic attribute  __dict__
# This will show all the attributes belonging to an object
# For example:

print(Item.__dict__)   # Class attributes
print(item1.__dict__)  # Instance level attributes

{'__module__': '__main__', 'pay_rate': 0.8, '__init__': <function Item.__init__ at 0x7fe71f30d4e0>, 'total_amount': <function Item.total_amount at 0x7fe71f30d580>, '__dict__': <attribute '__dict__' of 'Item' objects>, '__weakref__': <attribute '__weakref__' of 'Item' objects>, '__doc__': None}
{'name': 'Mobile', 'price': 400, 'quantity': 3}


In [9]:
# Discount on item 2
item2 = Item("Laptop", 1000, 5)
item2.apply_discount()
print(item2.price)

800.0


In [11]:
# Applying discount on a specific item 
item3 = Item("Charger", 100, 6)
item3.pay_rate = 0.7            # changing pay rate for a specific item by using class level attribute
item3.apply_discount()
print(item3.price)

70.0


In [34]:
# If we have a lot of items and we want to see all items together, we can use a list as a class level attribute
# we added all = [] list as a class level attribute
item1 = Item("Phone", 100, 1)
item2 = Item("Laptop", 1000, 3)
item3 = Item("Cable", 10, 5)
item4 = Item("Mouse", 50, 5)
item5 = Item("Keyboard", 75, 5)
print(Item.all)   # prints all the items in 'all' list

[Item(Phone, 100, 1), Item(Laptop, 1000, 3), Item(Cable, 10, 5), Item(Mouse, 50, 5), Item(Keyboard, 75, 5)]


In [18]:
# to print all the item names

for instances in Item.all:
    print(instances.name)     

Phone
Laptop
Cable
Mouse
Keyboard


### Adding csv method for creating instances and getting data from csv file
* This method will be a class method since we to create instances inside it, we will access it through class 

In [1]:
import csv

class Item:

    # Clas variables
    pay_rate = 0.8 # Pay after 20 % discount
    all = []

    def __init__(self, name: str, price: float, quantity = 0):
        
        # Validations on received arguments
        assert price>=0, f"Price {price} must be greater than or equal to zero"
        assert quantity>=0, f"Price {quantity} must be greater than or equal to zero"

        
        # Initiaizing Instance variables
        self.name = name
        self.price = price
        self.quantity = quantity

        self.all.append(self)


    @classmethod
    def instantiate_from_csv(cls):
        with open("items.csv", 'r') as f:
            reader = csv.DictReader(f)
            items = list(reader)

        for item in items:
            print(item)
            Item(
                name= item.get('name'), 
                 price=float(item.get('price')),
                 quantity=int(item.get('quantity'))
                 )


    def total_amount(self):
        return self.price * self.quantity
    

    def apply_discount(self):
        self.price = self.price * self.pay_rate   # Item.pay_rate can also be written   


    # for better representation of all the instance attributes we use __repr__  magic method inside class
    def __repr__(self) -> str:
        return f"Item({self.name}, {self.price}, {self.quantity})"
    


Item.instantiate_from_csv()

print(Item.all)

{'name': 'Phone', 'price': '100', 'quantity': '1'}
{'name': 'Laptop', 'price': '1000', 'quantity': '3'}
{'name': 'Cable', 'price': '10', 'quantity': '5'}
{'name': 'Mouse', 'price': '50', 'quantity': '5'}
{'name': 'Keyboard', 'price': '70', 'quantity': '5'}
[Item(Phone, 100.0, 1), Item(Laptop, 1000.0, 3), Item(Cable, 10.0, 5), Item(Mouse, 50.0, 5), Item(Keyboard, 70.0, 5)]


# Static Method

* Since the price values we are getting are in floats, there are some values like 100.0, 1000.0 or 10.0 . It's better to represent them in the form 100, 1000 or 10
* So we will create a static method to achieve this
* Static methods have a very clear use-case. When we need some functionality not w.r.t an Object but w.r.t the complete class, we make a method static. This is pretty much advantageous when we need to create Utility methods as they aren’t tied to an object lifecycle usually. Finally, note that in a static method, we don’t need the self to be passed as the first argument.
* We don't need to pass a class or an object as an argument to a static method

In [2]:
import csv

class Item:

    # Clas variables
    pay_rate = 0.8 # Pay after 20 % discount
    all = []

    def __init__(self, name: str, price: float, quantity = 0):
        
        # Validations on received arguments
        assert price>=0, f"Price {price} must be greater than or equal to zero"
        assert quantity>=0, f"Price {quantity} must be greater than or equal to zero"

        
        # Initiaizing Instance variables
        self.name = name
        self.price = price
        self.quantity = quantity

        self.all.append(self)


    @classmethod
    def instantiate_from_csv(cls):
        with open("items.csv", 'r') as f:
            reader = csv.DictReader(f)
            items = list(reader)

        for item in items:
            price_val = float(item.get('price'))

            if Item.is_integer(price_val):
                price_val = int(price_val)

            Item(
                name= item.get('name'), 
                 price= price_val,
                 quantity=int(item.get('quantity'))
                 )


    @staticmethod
    def is_integer(num):

        if isinstance(num, float):
            return num.is_integer()
        
        elif isinstance(num, int):
            return num.is_integer()   # The numbers like 7.0, 8.0, 100.0 will be considered as integers with this method
        
        else:
            False

    def total_amount(self):
        return self.price * self.quantity
    

    def apply_discount(self):
        self.price = self.price * self.pay_rate   # Item.pay_rate can also be written   


    # for better representation of all the instance attributes we use __repr__  magic method inside class
    def __repr__(self) -> str:
        return f"Item({self.name}, {self.price}, {self.quantity})"
    


Item.instantiate_from_csv()

print(Item.all)

[Item(Phone, 100, 1), Item(Laptop, 1000, 3), Item(Cable, 10, 5), Item(Mouse, 50, 5), Item(Keyboard, 70, 5)]


# Class method vs Static Method

The difference between the Class method and the static method is:

* A class method takes cls as the first parameter while a static method needs no specific parameters.
* A class method can access or modify the class state while a static method can’t access or modify it.
* In general, static methods know nothing about the class state. They are utility-type methods that take some parameters and work upon those parameters. On the other hand class methods must have class as a parameter.
* We use @classmethod decorator in python to create a class method and we use @staticmethod decorator to create a static method in python.


# When to use the class or static method?
* We generally use the class method to create factory methods. Factory methods return class objects ( similar to a constructor ) for different use cases.
* We generally use static methods to create utility functions.

In [3]:
# Example 
# Python program to demonstrate
# use of class method and static method.
from datetime import date


class Person:
	def __init__(self, name, age):
		self.name = name
		self.age = age

	# a class method to create a Person object by birth year.
	@classmethod
	def fromBirthYear(cls, name, year):
		return cls(name, date.today().year - year)

	# a static method to check if a Person is adult or not.
	@staticmethod
	def isAdult(age):
		return age > 18


person1 = Person('mayank', 21)
person2 = Person.fromBirthYear('mayank', 1996)

print(person1.age)
print(person2.age)

# print the result
print(Person.isAdult(22))


21
28
True


# Inheritance

In [15]:
import csv

class Item:

    # Clas variables
    pay_rate = 0.8 # Pay after 20 % discount
    all = []

    def __init__(self, name: str, price: float, quantity = 0):
        
        # Validations on received arguments
        assert price>=0, f"Price {price} must be greater than or equal to zero"
        assert quantity>=0, f"Price {quantity} must be greater than or equal to zero"

        
        # Initiaizing Instance variables
        self.name = name
        self.price = price
        self.quantity = quantity

        self.all.append(self)


    @classmethod
    def instantiate_from_csv(cls):
        with open("items.csv", 'r') as f:
            reader = csv.DictReader(f)
            items = list(reader)

        for item in items:
            price_val = float(item.get('price'))

            if Item.is_integer(price_val):
                price_val = int(price_val)

            Item(
                name= item.get('name'), 
                 price= price_val,
                 quantity=int(item.get('quantity'))
                 )


    @staticmethod
    def is_integer(num):

        if isinstance(num, float):
            return num.is_integer()
        
        elif isinstance(num, int):
            return num.is_integer()   # The numbers like 7.0, 8.0, 100.0 will be considered as integers with this method
        
        else:
            False

    def total_amount(self):
        return self.price * self.quantity
    

    def apply_discount(self):
        self.price = self.price * self.pay_rate   # Item.pay_rate can also be written   


    # for better representation of all the instance attributes we use __repr__  magic method inside class
    def __repr__(self) -> str:
        return f"Item({self.name}, {self.price}, {self.quantity}, {self.broken_phones})"
    


class Phone(Item):
    def __init__(self, name: str, price: float, quantity=0, broken_phones = 0):
        super().__init__(name, price, quantity)

        self.broken_phones = broken_phones

        #Phone.all.append(self)

   

phone1 = Phone("jscPhonev10", 500, 5, 1)
phone1.broken_phones = 1
phone2 = Phone("jscPhonev20", 700, 5, 1)
phone2.broken_phones = 1

print(Item.all)

[Item(jscPhonev10, 500, 5, 1), Item(jscPhonev20, 700, 5, 1)]


In [18]:
import csv

class Item:

    # Clas variables
    pay_rate = 0.8 # Pay after 20 % discount
    all = []

    def __init__(self, name: str, price: float, quantity = 0):
        
        # Validations on received arguments
        assert price>=0, f"Price {price} must be greater than or equal to zero"
        assert quantity>=0, f"Price {quantity} must be greater than or equal to zero"

        
        # Initiaizing Instance variables
        self.name = name
        self.price = price
        self.quantity = quantity

        self.all.append(self)


    @classmethod
    def instantiate_from_csv(cls):
        with open("items.csv", 'r') as f:
            reader = csv.DictReader(f)
            items = list(reader)

        for item in items:
            price_val = float(item.get('price'))

            if Item.is_integer(price_val):
                price_val = int(price_val)

            Item(
                name= item.get('name'), 
                 price= price_val,
                 quantity=int(item.get('quantity'))
                 )


    @staticmethod
    def is_integer(num):

        if isinstance(num, float):
            return num.is_integer()
        
        elif isinstance(num, int):
            return num.is_integer()   # The numbers like 7.0, 8.0, 100.0 will be considered as integers with this method
        
        else:
            False

    def total_amount(self):
        return self.price * self.quantity
    

    def apply_discount(self):
        self.price = self.price * self.pay_rate   # Item.pay_rate can also be written   


    # for better representation of all the instance attributes we use __repr__  magic method inside class
    def __repr__(self) -> str:
        return f"Item({self.name}, {self.price}, {self.quantity}, {self.broken_phones})"
    


class Phone(Item):
    def __init__(self, name: str, price: float, quantity=0, broken_phones = 0):
        super().__init__(name, price, quantity)

        self.broken_phones = broken_phones

        Phone.all.append(self)

   

phone1 = Phone("jscPhonev10", 500, 5, 1)
phone1.broken_phones = 1
phone2 = Phone("jscPhonev20", 700, 5, 1)
phone2.broken_phones = 1

print(Item.all)

[Item(jscPhonev10, 500, 5, 1), Item(jscPhonev20, 700, 5, 1)]


In [23]:
import csv

class Item:
    pay_rate = 0.8  # Pay after 20% discount
    all = []

    def __init__(self, name: str, price: float, quantity=0):
        # Validations on received arguments
        assert price >= 0, f"Price {price} must be greater than or equal to zero"
        assert quantity >= 0, f"Quantity {quantity} must be greater than or equal to zero"

        # Initializing instance variables
        self.name = name
        self.price = price
        self.quantity = quantity

        # Append the new instance to the class-level list
        Item.all.append(self)

    @classmethod
    def instantiate_from_csv(cls):
        with open("items.csv", 'r') as f:
            reader = csv.DictReader(f)
            items = list(reader)

        for item in items:
            price_val = float(item.get('price'))

            if Item.is_integer(price_val):
                price_val = int(price_val)

            Item(
                name=item.get('name'),
                price=price_val,
                quantity=int(item.get('quantity'))
            )

    @staticmethod
    def is_integer(num):
        if isinstance(num, float):
            return num.is_integer()
        elif isinstance(num, int):
            return num.is_integer()  # The numbers like 7.0, 8.0, 100.0 will be considered as integers with this method
        else:
            return False

    def total_amount(self):
        return self.price * self.quantity

    def apply_discount(self):
        self.price = self.price * self.pay_rate  # Item.pay_rate can also be written

    # for better representation of all the instance attributes we use __repr__ magic method inside class
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}({self.name}, {self.price}, {self.quantity})"


class Phone(Item):
    def __init__(self, name: str, price: float, quantity=0, broken_phones=0):
        super().__init__(name, price, quantity)

        assert broken_phones >= 0, f"Quantity {broken_phones} must be greater than or equal to zero"

        self.broken_phones = broken_phones

        # changing the value of quantity by subtracting broken phones
        self.quantity = quantity - broken_phones



phone1 = Phone("jscPhonev10", 500, 5, 1)
phone2 = Phone("jscPhonev20", 700, 5, 1)

print(Item.all)
print(Phone.all)


[Phone(jscPhonev10, 500, 4), Phone(jscPhonev20, 700, 4)]
[Phone(jscPhonev10, 500, 4), Phone(jscPhonev20, 700, 4)]


In [ ]:
class Item:
    
    pay_rate = 0.8
    all = []

    def __init__(self, name : str, price : float, quantity = 0) :
        
        # Enter validations on the instance arguments
        assert price >= 0 , f"Price {price} is not greater than or equal to zero"
        assert quantity >=0 , f"Quantity {quantity} is not greater than or equal to zero"

        # Initializing instance objects
        self.name = name
        self.price = price
        self.quantity = quantity


        Item.all.append(self)

    def calculate_total_price(self):
        return self.price * self.quantity
    
    def apply_discount(self):
        self.price = self.price * self.pay_rate

    def __repr__(self) :
        return 

